application: tomato-dev01
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: (.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: \1
  upload: (.*\.html)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: \1
  upload: (.*\.js)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: \1
  upload: (.*\.txt)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: \1
  upload: (.*\.xml)

# other files
- url: /(.*\..*)
  static_files: \1
  upload: (.*\..*)

# index files
- url: /samples
  static_files: index-samples.html
  upload: index-samples.html

#- url: /(.+)/
#  static_files: \1/index.html
#  upload: (.+)/index.html

- url: /
  static_files: index.html
  upload: index.html
  secure: always
