application: tomato-dev01
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: PIL
  version: "1.1.7"
- name: webob
  version: "1.2.3"
- name: lxml
  version: "2.3"

handlers:
- url: /api/.*
  script: _app.application
  secure: always

- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: (.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: \1
  upload: (.*\.html)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: \1
  upload: (.*\.js)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: \1
  upload: (.*\.txt)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: \1
  upload: (.*\.xml)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: \1
  upload: (.*\.(bmp|gif|ico|jpeg|jpg|png))

# resources
- url: /resources/(.*\..*)
  static_files: resources/\1
  upload: resources/(.*\..*)

# index files
- url: /samples
  static_files: index-samples.html
  upload: index-samples.html

- url: /
  static_files: index.html
  upload: index.html
  secure: always
