application: unity-one
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: PIL
  version: "1.1.7"
- name: webob
  version: "1.2.3"
- name: lxml
  version: "2.3"
- name: webapp2
  version: "2.5.2"

handlers:
- url: /api/.*
  script: tomato.application
  secure: always

- url: /(.*\.css)
  mime_type: text/css
  static_files: _static/\1
  upload: _static/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: _static/\1
  upload: _static/(.*\.html)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: _static/\1
  upload: _static/(.*\.js)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: _static/\1
  upload: _static/(.*\.txt)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: _static/\1
  upload: _static/(.*\.xml)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: _static/\1
  upload: _static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /(.*\.(svg|woff|ttf))
  static_files: _static/\1
  upload: _static/(.*\.(svg|woff|ttf))

# other resources
- url: /static/(.*\..*)
  static_files: _static/\1
  upload: _static/(.*\..*)

# index files
- url: /samples
  static_files: _static/index-samples.html
  upload: _static/index-samples.html

- url: /
  static_files: _static/index.html
  upload: _static/index.html
  secure: always
